language: rust
rust: 1.0.0-alpha.2

before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi

script: make build/main.elf
